# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KlokeAlg <- function(sample, set, sigma, omega, iter, step) {
    .Call('_denoiseTDA_KlokeAlg', PACKAGE = 'denoiseTDA', sample, set, sigma, omega, iter, step)
}

MeanShiftAlg <- function(set, sigma, iter, step) {
    .Call('_denoiseTDA_MeanShiftAlg', PACKAGE = 'denoiseTDA', set, sigma, iter, step)
}

KDE <- function(set, sigma) {
    .Call('_denoiseTDA_KDE', PACKAGE = 'denoiseTDA', set, sigma)
}

